### ISSUE TITLE
Switch to Vue3.0

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#1100]

**Comment by martinmaillard** [comment]
Some notes about libraries before upgrading:

### Buefy will not support Vue 3

Proposed solution: switch to Oruga https://github.com/zazuko/cube-creator/pull/1120

### vue-class-component, vue-property-decorator, vuex-class don't support Vue 3 yet
 
If I remember correctly, we chose to use these libraries because it improved Typescript support with Vue 2. Vue 3 has much better Typescript support out of the box.

After 2 years working on this project, I can say that using a non-official way of declaring components was mostly frustrating. Using classes felt more natural at the beginning, but it turns out that using a different API than 100% of documentation out there means you always have to translate in your head. It's not great.

I would propose to get rid of these libraries and to switch back to the official way to define components. It will cause a bit of work now, but I'm sure it will simplify maintenance in the long run.

### vue-color, vue-markdown and vuex-oidc

Vue 3 support is uncertain for these libraries. We'll need to check and potentially find alternatives.

(I read somewhere in an issue comment that vuex-oidc works with Vue3)

### vue-custom-element

I don't think it supports Vue 3. But there is now an [offial package for custom elements](https://github.com/vuejs/vue-web-component-wrapper). We'll need to migrate.

### vuex, vue-router and vue-select have a Vue 3 version

We'll need to upgrade/migrate.
