### ISSUE TITLE
First interface to allow automatic mapping 

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#1101]
Create method (with SPARQL updates) to allow the user to choose the "predicate" of the Shared Dimension with the exact match of the string to map automatically all fields in a dimension.

Batch Mapping:
  * Choose which Shared Dimension to match to.
  * Choose the predicate of Shared Dimension to match to. (optionally with schema:identifiers also listed only if `schema:identifier` -> `schema:value` / https://register.ld.admin.ch/zefix/company/1198554/UID/CHE242294601)
  * "Process"

**Comment by AFoletti** [comment]
If I may, the BFE has a concrete usecase for that. We would like to go to prod mid-May with a dataset having >300 objects to map.
Of course, we will do the mapping manually if needed. But if this can be deployed to prod beforehand it would be a great help 😄

**Comment by l00mi** [comment]
@AFoletti @AFoletti could you test this functionality? It is on INT available now. There is no documentation, please ask if you need help to use it.

**Comment by AFoletti** [comment]
@l00mi 
The functionality seems to work pretty fine. And is actually a godsent since the mapping was a chore beforehand 😉 . Many thanks for implementing this!

Still, a couple of things worth mentioning:

a) the automap button is hidden at the bottom of the interface, and when you have lots of entries you do not see it if you do not scroll down. Why not here? 
![image](https://user-images.githubusercontent.com/691243/170625104-057e26cd-a629-4311-b924-3386b79fd8a5.png)

b) when you get the automapping interface, it automatically finds the matching ID (cool!). However, you still have a drop-down menu for picking the shared dimension. Why? And why is it not already filled since I choose the shared dimension the step before? This is a little confusing and I think it may easily be forgotten. Please either remove this drop-down of prefill it with the choice I made the step before.

c) This checkbox (present in both the first step and the automated mapping one) is a little confusing. Why do I need it? If my data does not contain deprecated IDs, it is not a question I am interested in ("_of course I do not want to see those deprecated terms_"). And if it does, I _need_ those deprecated terms in any case since to my understanding you cannot publish partly mapped data. As a result, the question is in my opinion not really needed and could be removed. 
![image](https://user-images.githubusercontent.com/691243/170626587-dbfeca79-ec11-4fbe-a184-33751d632d0f.png)


A side note: I tested with WASTA and there are a dozen IDs that could not be mapped (e.g: 101570, 104160). Those are not present in the stopo triplestore (PROD nor DEV). I have to check with Pasquale the reason why but my question to you is: what now? How can I use my data on LINDAS? Do I really need to remove those IDs from my dataset until they can be mapped?
