### ISSUE TITLE
Doubling of shape contraints with publish on INT

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#1218]
With an import project:

https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!ubd0066import-de-prod-1lmakvo9eek/publication
https://s.zazuko.com/fADRv3

**Comment by l00mi** [comment]
Do we have any hint why this could happen?

**Comment by Rdataflow** [comment]
yet another example of trippled key dimensions...
job https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/30832
from proj https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!nfi4-total-basal-area-of-main-tree-species-in-production-regions-no-hierarchy-rdwdmlrzn3o/edit
describe cube:Constraint https://s.zazuko.com/hGgLy
@tpluscode how to fix this?

**Comment by Rdataflow** [comment]
currently also @kronmar is impacted by this. 
@tpluscode can you have a look at this ...

**Comment by tpluscode** [comment]
I am again unable to reproduce when running the data pipeline locally. Looking at the job listing I think it looks like the issue is same version running publish simultaneously. 

It is not possible to proactively prevent parallel jobs because of a waiting period before GitLab picks up a jobs and the pipeline actually starts. What I can try is to add a runtime check to forcibly stop a job if a newer publication of same cube version starts
