### ISSUE TITLE
Mapper: upload CSV file

### ISSUE THREAD

**Issue by martinmaillard** [zazuko/cube-creator#13]
In the mapper, users need to be able to upload a CSV file.

- The file will be stored in a pre-defined S3 bucket
- It must handle large files
- A sample of the file must be extracted and stored somewhere

**Comment by tpluscode** [comment]
I don't think we need to extract the sample. 

If we intend to have the files always accessible from S3 it would be simpler to simply open a stream directly from storage and read a portion. This would even allow running the preview on any arbitrary subset of rows from anywhere in the csv

**Comment by lucafurrer** [comment]
One mapping can have more than one file, correct?

**Comment by lucafurrer** [comment]
Open questions to be discussed/approved

**Workflow**: 
1. When creating a project starting from a CSV, a new cube with a node csv-mapping is created. 
2. The user uploads csv files. Is it possible to have several files
a) We have to use a stream to be able to store big files
b) The location of the file has to be attached to the node node csv-mapping
3. The user starts the mapping -> other task

**Buckets**
Are all files stored in the same bucket? As far as I understood yes.
If yes, with a folder per project? Would be useful when looking at the bucket

**API**
Since we have to use a stream.
Do we post a stream and the backend uploads the file and creates the needed nodes. How do we communicate the node
Or should there be a turnarond to the UI
1. Upload file and get location
2. Save location in Graph

**Graph**
Is there more than one file per csv-mapping?
Does every upload have node with link to the file location, and later on the mapping?

**Comment by lucafurrer** [comment]
@tpluscode @martinmaillard @vhf These are the questions open for me with respect to the csv upload. 
Is there a need for a meeting or should we first discuss this here?

**Comment by vhf** [comment]
Open questions to be discussed/approved

**Workflow**: 
1. *When creating a project starting from a CSV, a new cube with a node csv-mapping is created.*
  -> creating a project should not automatically create a CSV mapping but we might later on give the user the option to create a project with an initial CSV mapping
2. *The user uploads csv files. Is it possible to have several files* Yes
  a. We have to use a stream to be able to store big files
  b. The location of the file has to be attached to the node node csv-mapping
3. The user starts the mapping -> other task

**Buckets**
Are all files stored in the same bucket? As far as I understood yes.
If yes, with a folder per project? Would be useful when looking at the bucket

**API**
Since we have to use a stream.
Do we post a stream and the backend uploads the file and creates the needed nodes. How do we communicate the node
Or should there be a turnarond to the UI
1. Upload file and get location
2. Save location in Graph

**Graph**
Is there more than one file per csv-mapping?
Does every upload have node with link to the file location, and later on the mapping?

**Comment by lucafurrer** [comment]
I think the only point left is part of #62. Or am I missing something?
