### ISSUE TITLE
Creating a Shared Dimension fails - Blocker

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#1319]
Cube Creator version 1.12.9
Tried on TEST and INT

![image](https://user-images.githubusercontent.com/6167669/198554085-6dfcd5ac-ab62-43f7-9fe4-db3061bb4055.png)

**Comment by FabianCretton** [comment]
and same remark as always: would it be possible to get real information when an error occurs ?

**Comment by FabianCretton** [comment]
another question: don't you have any validation test, unit tests, acceptance tets, etc... so that we do not go back in time when features that work become unstable later ? a honest question, I am interested in what exists and how the system is tested

**Comment by FabianCretton** [comment]
@l00mi any update on this ? 
My only workaround so far is to show Tobias how to create Shared Dimension through .trig upload

**Comment by l00mi** [comment]
@tpluscode did some work here, not sure if this is fixed too. @tpluscode ?

**Comment by tpluscode** [comment]
The reason here is simple. When created using the form, the "identifier" field is required to consist only of letters, number and a hyphen.

This is nothing new, as well as the lacking display of errors which is unfortunately problematic with more complex SHACL shapes. Interestingly too, it was never caught that the shared dimension import does not put the same restriction on the identifier property.

In that regard, is that validation unnecessarily strict maybe and should be relaxed? @l00mi

**Comment by l00mi** [comment]
Lets add the underscores to the allowed characters to be in sync with the field.
