### ISSUE TITLE
[URGENT] Creating a mapping to another table seems to no more work

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#1358]
I will give a Cube Creator class next tuesday, and thus "urgent"
Sorry if it is my mistake, but I do not understand what is happening
Tried on two projects:
- https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!fabtesttablemapping-rzlj5evel6x/csv-mapping
- https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!fab-rl-no-numeric-measure-newvk8l3wpn/csv-mapping

Cube Creator Version: 1.13.2
Tried on FireFox 108.0.2 and Edge 108
See printscreen: when clicking on Create Link button, nothing happens
![image](https://user-images.githubusercontent.com/6167669/212006507-30291c08-897e-410f-ad26-de7a5183e2fd.png)

If it is a bug, I do have one question: how is the application automatically "tested" when a new release is done ?

**Comment by tpluscode** [comment]
Sorry about that @FabianCretton. It was a simple problem of reacting to the user click on that button

We do have a Cypress test case for this. As it turned out, it [did not accurately emulate user action](https://github.com/zazuko/cube-creator/pull/1359/files#diff-c6dec7e39baa369219b346ca713800e99352d0789cf3611e588e83ae46034d16L174-L175), which is why the test still passed but the functionality was still broken

I fixed both in a PR

**Comment by FabianCretton** [comment]
Thank you @tpluscode 
And very nice to know that tests are automatically performed.

Will the PR be released today ?

**Comment by tpluscode** [comment]
Yes, we can release any time now
