### ISSUE TITLE
Improve User field Search

### ISSUE THREAD

**Issue by dabo505** [zazuko/cube-creator#1403]
User list should be sorted and the search functionality improved.

**Comment by tpluscode** [comment]
The users on the project search form are now sorted alphabetically. I also fixed the behaviour which reset the search and loaded all projects when the "New project" button was clicked

Since there are a few users already, in PR #1421 I started switching to an autocomplete field (with search) but it has a problem I could not yet identify that the dropdown sometimes does not appear and requires additional clicks on the field itself.

Interestingly, I could not reproduce this on my second computer today. Maybe we could release that too and see how it works?

https://user-images.githubusercontent.com/588128/233972378-9542659d-cb46-4907-beba-03281e036b59.mp4
