### ISSUE TITLE
Project cannot be imported in INT

### ISSUE THREAD

**Issue by ortnever** [zazuko/cube-creator#1434]
I tried to import a project from PROD to INT but an error occured.

* [ ] Other : New project -> from exported project

**To Reproduce**
1. Export project "ubd0066" from PROD
2. Import it as new Project with new Name and new id in INT

![image](https://github.com/zazuko/cube-creator/assets/79834090/08a237a9-7d4f-41ab-99fb-ece682321c22)

**Comment by tpluscode** [comment]
Uh, took me a moment to figure out because the message is quite misleading here again.

The problem is that the mappings for some columns in table **Station** have datatype `xsd:int` which is not in the allowed set. Instead, `xsd:integer` in expected.

If I recall correctly, some time in ago we made that change. I see it was in 2021. This project likely predates the change?

To make it work, please adjust the columns and then export.
