### ISSUE TITLE
Edit Raw RDF option in Cube Creator

### ISSUE THREAD

**Issue by tboeni** [zazuko/cube-creator#1467]
This might be more a question if not a bug report. 
I was trying out the option of editing the raw RDF in Cube Creator when doing some Shared Dimensions. 

However when I tried to insert an option "schema:url" it would tell me that it successfully saved the RDF but would vanish from the Edit page whenever I opened it again.

![Forest NOGA Edit RAW RDF](https://github.com/zazuko/cube-creator/assets/111350367/b3bf07f5-7835-4c4e-b6dc-96faef48af30)

Is this kind of editing not supported right now or did I do it wrongly?

**Comment by tpluscode** [comment]
The input is not lost. If you were to query that term in Lindas you will find it.

The additional property does not appear when the edit page is reopened because only properties exactly listed in the shared term definition are retrieved from the API.

You can edit the shared dimension and add a new property on the `Term properties` tab. When saved, you will then find that property in the term edit form.
