### ISSUE TITLE
Usability: Edit-Form keeps value after Cancel-Event

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#336]
Steps to reproduce:

- Click "Edit" on a Column of an Output Table in CSV Mapping
- Change any property (like Name, Datatype, ...)
- Click "Cancel"
- Click "Edit" on another Column 
- Click "Cancel"
- Click "Edit" once again on the initial Column: 
  - Bug: The values that were cancelled are still there
  - OK: These "wrong" values are not saved when another part of the mapping is saved

**Comment by FabianCretton** [comment]
This is still an issue in "Edit column mapping", and it is "tricky".
The comment of Daniel seems not true: "OK: These "wrong" values are not saved when another part of the mapping is saved"
Example:
- I edit a column and change its type from int to bool
- I cancel because it was not what I want (int was correct)
- I edit the column once again later, because I want to change the target property
- Here is the problem: the type is still bool (the cancelled value)
- If I save now, because I changed the target property -> the type will be changed to bool -> very tricky

I guess it is a bug, and it should be easy to fill the values of the edited column with the correct values, each time that the column is edited, as it is done the first time the column is edited ?

**Comment by l00mi** [comment]
@tpluscode can you have a look please?
