### ISSUE TITLE
Usability: Enter on autocomplete triggers submit

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#339]
Steps to reproduce:

- Edit Column Mapping in CSV Mapping
- type f. ex. "sch" into Target Property
- Select one of the suggestions using the cursor keys
- Hit Enter
  - Submit is triggered, which it shouldn't

Note: This really is some of the lowest priority issues ;-)

**Comment by danielmittag** [comment]
Original report by Fabian

![GitHubIssue_339](https://user-images.githubusercontent.com/17119538/102081052-dc83f880-3e0f-11eb-94eb-38431b42646b.png)

**Comment by FabianCretton** [comment]
Will this finally stay "as is" ? I got myself "caught" again yesterday when editing some data and validating a choice in a drop-down list with "ENTER" -> which did trigger the "save" button instead of just validating my choice.
If it is a lot of work to correct this, I guess it should stay a nice to have (users will get used to it). But if it is not so hard to correct, it does make sense to correct it, no ?
I am also guessing you are using a java-script library for this, is this a "normal" behavior of that library ?
