### ISSUE TITLE
Add the table name to the prefix in the case of an internal identifier (no http(s):// in the uri).

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#421]
- [ ] In a table if the {Identifier template} is not absolute (no http(s):// in the uri) add the table name between the cube uri and the identifier itself.

- [ ] Show the composed URI below the field. Similar to the one below found in **Edit column mapping**

![Screenshot 2021-01-18 at 17 00 58](https://user-images.githubusercontent.com/502518/104938026-c89f5980-59ae-11eb-8513-ef234efc68c1.png)

**Comment by martinmaillard** [comment]
I don't really like the idea of having this hardcoded in the backend because it limits the options quite a bit.

In the v1 of the tool, this field was pre-filled by the UI: when entering the table name, it would pre-fill the identifier input with something like `<table-name>/{REPLACE}` and then provide an auto-complete for column names between "{}". It was not perfect, but already better than not helping the user at all.

I can try to reproduce this in the new tool. But I'm not sure I'll be able to because of the SHACL-generated form.

**Comment by l00mi** [comment]
I think it is a valid solution to pre-fill. Please try.
