### ISSUE TITLE
Cube Designer should also be available for dimension tables

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#431]
Currently the Cube Designer allows setting `Name`, `Scale of Measure` and `Description` for all Dimension properties of the **observation table**. 
There is no reason why this shouldn't be possible or even required for the properties of the **dimension tables**.

From a UI perspective a dropdown list with all the tables (next to the language selector) would do it imo.

**Comment by l00mi** [comment]
The argumentation to no have it for the non observation tables would be to make it clear which is the cube. And what are "only" auxiliary information. We do not want to evoke the feeling that we create multiple cubes.

Through the panel on the left side the other dimension values can be discovered.

I imagine this issue comes from the "need" to check if the values in the non observation table are correct in a more effective way. This might be an issue to look into after the MVP.

**Comment by danielmittag** [comment]
A more specific example: 
- In the **CSV Mapping** for the observation table in UDB0028 we have properties like "value" or "pollutant".
  - --> In the **Cube Designer** we then define the labels in 4 languages (D: "Wert", "Schadstoff")
- In the **CSV Mapping** for the dimension table "polluntants" we have properties like "name" and "description"
  - --> We currently **don't have a way to set the labels** in 4 languages ("Name", "Beschreibung") and I think it is clear that these properties will have to be displayed by visualize

**Comment by l00mi** [comment]
We have a way to see this.. if you click on a Pollutant in the UDB0028 table, it shows the object with all properties, in multiple languages. Further you can even navigate in other values.

**Comment by l00mi** [comment]
As discussed. Only the main cube observation table is shown. The other connected tables can be browsed.
