### ISSUE TITLE
Cube transformation seems slow for "not so big" datasets

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#564]
There was an improvement for the transformation process when putting into place an idle VM (done a few weeks ago, Michael asked about this to VSHN). However, I was only testing with a very small dataset.

But still today, with my "Fabian_Jahrbuch Wald & Holz 2020_Test 2", it seems that the transformation still takes about 5-6 minutes for this 8 to 15MB file. 
I can not check yet how many triples are generated (I will create a next issue about this), but I am sure that the transformation of even bigger dataset could take only a few seconds (not talking about VM handling, etc.).
Could this be investigated ?
My observation: 
There are two phases during a transformation, from a user point of view: during the first part the "log" is not available, and after a while the "log" link becomes visible and a blue icon blinks. This second phase when the blue icon blinks seems pretty long. Also: during this second phase I see once again a "downloading csv" step, which was already performed before, why that ?

**Comment by tpluscode** [comment]
I mentioned this earlier, that most of the transformation time is in fact spent on uploading the triples to Stardog.

Here's a timeline of your transformation

<img width="943" alt="Screenshot 2021-03-03 at 18 08 34" src="https://user-images.githubusercontent.com/588128/109843601-87f05c80-7c4b-11eb-8532-ccd740ccffbb.png">

The longest bars are requests to Stardog. Do notice that the transformation otherwise progresses in parallel, thus most of the overall time is in fact the sum of Stardog uploads with little else

> Also: during this second phase I see once again a "downloading csv" step, which was already performed before, why that ?

Every output table is processed totally independently. It means that every time its source CSV will be opened again from S3 (download is not entirely accurate given the contents are streamed).

This may seem suboptimal but it looks like the overhead is negligible at this time.

**Comment by FabianCretton** [comment]
Thank you for your reply, I did not "catch" that.

Once I can see how many triples are generated/uploaded, I will have a better understanding of this.

Then, I am thinking that when someone prepares a cube, he might want to first work with a very small version of the dataset, prepare everything, transform and work on the Cube Designer to see the results and prepare the metadata. And only then, when everything looks fine, replace the .csv with the original dataset.
@l00mi Is this something that should be proposed in the User Documentation ?

**Comment by l00mi** [comment]
That might make sense, but only for big datasets to beginn with. Also I would like to investigate how we can reduce the time of the upload to Stardog. This seems excessive as it is now.

@ktk what are reasonable PUT times for such datasets? Do we have also a pipeline which works with the LOAD strategy?

**Comment by tpluscode** [comment]
We considered a "preview" feature in the beginning which would operate only on subset of the input data but it quickly becomes obvious that it can produce misleading results. Especially if a cube is composed of multiple CSVs, the output can in fact be a broken cube if one is not careful. Also, issues could appear far in the input data which makes it difficult to choose the "right" subset.

That said, while we did not consider such usage, it could be possible to start working from a manually prepared reduced input. Then, when they are happy with what they have, they would upload the complete CSVs and run the complete transformation.

**Comment by ktk** [comment]
@l00mi no we don't do LOAD anymore. Stardog is in general not fast for loading triples via Graph Store protocol. I once need to benchmark doing it locally via graph store and via stardog cli though.

I agree that 5-8 mins is long for such a small dataset but then again do we care? I mean it's generated automatically so it's not blocking anyone or anything, does it?

**Comment by l00mi** [comment]
@ktk I now that we don't use LOAD anymore. But why?

The problem here is that we do between the CSV Mapping one step of transformation, with the idea to check afterwards if it was mapped correctly. This is expected to be "interactive" that you can iterate on your mapping.

While I don't see a need to have it in the ms range, but it should stay below 1 minute to be usable.

**Comment by ktk** [comment]
I did some extensive benchmarking on my local machine, see results [here](https://gist.github.com/ktk/612cf044231245296cb1c45651285993).

Conclusion: I do not see a big difference between the methods, with the exception of non-streaming `PUT`, that seems to add an overhead. But we do not do that with `barnard59`, it is chunking there (stream).

What I did not test is doing the same thing with `barnard59`. I think we might need the dump in RDFJS serialization to really performance-test the interface for that.

**Comment by ktk** [comment]
Updated now with `barnard59` like version. A lot slower but that is because it is doing something with the data. What we should compare as well is how long the pipeline runs without writing to graph store but to `stdout` or file instead, can you test that?

**Comment by l00mi** [comment]
Current Issue https://control.vshn.net/tickets/SBAR-480

**Comment by l00mi** [comment]
we track this overall problem with #827
