### ISSUE TITLE
Count passing quads in pipeline

### ISSUE THREAD

**Issue by tpluscode** [zazuko/cube-creator#569]
Once I can see how many triples are generated/uploaded, I will have a better understanding of this.

_Originally posted by @FabianCretton in https://github.com/zazuko/cube-creator/issues/564#issuecomment-790346028_

**Comment by FabianCretton** [comment]
I am not sure that we really need a new feature here.

But this might be related to something needed by the user:
As a user, how do I know that my CSV file, with 54'372 lines, was correctly/fully transformed to RDF ?
If a successful transformation guaranties that all lines were converted to RDF, than nothing else is needed -> and we will add that information to the User Documentation.

Otherwise, if a pipeline can run successfully, but skipping some lines, the end-user need to know about this.
The more helpful would be to see the lines of the CSV with errors, does barnard59 provide this ?
Otherwise, something less helpful but easier to implement could be to show the number of observations on the Cube Designer.
The user can then compare the number of observations with the number of lines in the original CSV.
And this is related to https://github.com/zazuko/cube-creator/issues/533

**Comment by l00mi** [comment]
Solved with better errors on problems in pipeline.
