### ISSUE TITLE
Big Files

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#663]
Files surpassing the 100mb.

**Comment by l00mi** [comment]
## CSV Upload (exoscale s3) (5d)
  * (directly to S3) with pre-signed address
  * chunking / resumable upload
  * cube creator UI does facilitate the upload
    * it gets the upload link
    * it checks the browser upload flow
    * if succeeded from UI point of view it triggers the parsing
  * (optional) give a visual feedback on the upload 

## Pipeline
  * optimization to not download same file multiple times? (2d)
    * store on disk (problematic)
    * create smart pipeline chaining the different tasks (parallel stages?)
  * deduplication (push the limit up)
  * check keepalive of stardog?

**Comment by l00mi** [comment]
## CSV Upload
- chunking / resume upload
- 
## Pipelines
- parralel pipelines
- deduplication
- keep alive

**Comment by martinmaillard** [comment]
I did a bit of research on how we can implement this and there are 2 solutions with a big difference in complexity:

## 1. Use one pre-signed URL to upload the file from the UI

This is the less complex one because it is still "stateless". 
- UI asks API for a pre-signed URL for the file
- UI uploads the file
- UI sends the reference back to the API that will then start the parsing

The downside is that **we don't get "resumable uploads"**.

The size limit on AWS S3 is 5G, but not sure it's the same on the service we use.

## 2. Chunk the file and use a pre-signed URL for each chunk

This one is more complex because it requires generating an "upload ID" (and storing it somewhere)
- UI asks API to initiate an upload, UI provides an upload ID (or stores it)
- UI chunks the file. For each chunk, it asks API for a pre-signed URL
- UI uploads each chunk
- UI tells the backend that the upload is finished. API tells S3 that the upload is complete, and then downloads and parses the file.

This means we need to manage upload IDs, failed chunk uploads, etc.

We can implement resumable uploads with this solution. And I think there is no size limit.

**Comment by martinmaillard** [comment]
TODO:
- [ ] Check if we can use the File API to get resumable uploads without going directly to S3 (https://github.com/23/resumable.js)
- Another option is to offer a parallel solution to upload files directly to S3 without going through the web UI
