### ISSUE TITLE
Source wikipedia for resource labels

### ISSUE THREAD

**Issue by tpluscode** [zazuko/cube-creator#702]
I would propose to add `https://query.wikidata.org/sparql` here too for the time being?

_Originally posted by @l00mi in https://github.com/zazuko/cube-creator/issues/698#issuecomment-832565018_

**Comment by tpluscode** [comment]
@l00mi it can be done easily, I think, depending on the expectation.

I propose we hard-code that in the UI app itself, to run a query against Wikidata. Like this?

```sparql
construct { 
  <http://www.wikidata.org/entity/Q682> schema:name ?itemLabel
} where {
  <http://www.wikidata.org/entity/Q682> rdfs:label ?itemLabel
    
  filter( lang(?itemLabel) in ( "en", "de", "fr", "rm", "it" ))
}
```

**Comment by l00mi** [comment]
Yes. exactly UI app itself.

Just wondering as we will have more often the case that there is actually `rdfs:label` instead of `schema:name`, can we make the UI first expect former and if not available look for `rdfs:label`.

PS: Also its pretty interesting that DESCRIBE does not deliver `schema:name` where as dereferencing does ...
