### ISSUE TITLE
SharedDimensions linking: add filter in select box to link values

### ISSUE THREAD

**Issue by martinmaillard** [zazuko/cube-creator#743]
When linking values of a dimension to values of a shared dimension, all the values of the shared dimension are currently loaded in a select box.
<img width="321" alt="Screenshot 2021-05-26 at 09 42 06" src="https://user-images.githubusercontent.com/1334124/119621745-c474c400-be06-11eb-8fd5-511f2f5860f9.png">

This is ok for small dimensions, but not usable when we have thousands of values. The idea is to replace the select box with a filter that dynamically loads values based on what the user types.

**Comment by tpluscode** [comment]
We currently load the dropdown values from a `hydra:search` templated link described in the [shape](https://github.com/zazuko/cube-creator/blob/master/apis/core/bootstrap/shapes/dimension.ts#L291-L302) like

```turtle
[
  hydra:search [
    sh:path [ 
      sh:inversePath prov:hadDictionaryMember
    ] ;
    hydra:variableRepresentation hydra:ExplicitRepresentation ;
    hydra:template "dimension/_terms{?dimension}" ;
    hydra:mapping [
       hydra:variable "dimension" ;
       hydra:property cc:sharedDimension ;
       hydra:required true ;
    ] ;
  ]
]
```

This takes the selected dimension (`sh:path/sh:inversePath`) and applies it to the URI template, thus filtering only terms from the given dimension.

What we need now is to add a [`hydra:freetextQuery`](http://www.hydra-cg.com/spec/latest/core/#hydra:freetextQuery) to build a dynamically filtered dropdown. Changes will be required in Alcaeus so that multiple models can be combined to build the template

```js
// The form's focus node
let focusNode: GraphPointer
// the text value from the dropdown
let userInput: string
// the search template
let template: UriTemplate

// create a second model for the URI Template
const freeText = clownface().blankNode().addOut(hydra.freetextQuery, userInput)

// New Feature in Alcaeus and Shaperone
// Pass both pointers inside and combine them to construct the URI
template.expand(focusNode, freeText)
```

**Comment by tpluscode** [comment]
I think we might also consider hard-limiting the returned term count to say, 100?
