### ISSUE TITLE
imported project blames uploaded csv for corrupt line

### ISSUE THREAD

**Issue by Rdataflow** [zazuko/cube-creator#840]
**steps to reproduce**
1. export this project https://pipelines-test.lindas.admin.ch/app/cube-projects/cube-project!!ch-bafu-wald-faostat-prod-test002-xxqnddvzz4b/edit
2. download csv `Forestry_E_All_Data_(Normalized).csv`
3. import this project (i.e. in integ)
4. reupload the downloaded csv `Forestry_E_All_Data_(Normalized).csv`

**actual result**
![image](https://user-images.githubusercontent.com/26090254/133467618-bf4c62c3-4382-412d-9f02-511cfa5da5bc.png)

**expected result**
pass, based on the files content. > see L499-501
![image](https://user-images.githubusercontent.com/26090254/133468055-e476c9f6-5fcd-4d21-bdfd-925f19f3169d.png)

**Comment by tpluscode** [comment]
Thank you for reporting this. Again, as I think we've already seen this problem in distant past.

This time I managed to find the issue and turns out that Windows-style line-endings are to blame, not being handled correctly by our parsing routine. 

Not related to import/export after all - a fix is on its way

**Comment by Rdataflow** [comment]
Thank you for this hint and the fix already in review 👍

**Comment by Rdataflow** [comment]
@tpluscode Thank you for this fix.
