### ISSUE TITLE
Cube Creator - download CSV sometimes causes problems now

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#861]
On project https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!ubd0066-bodenbelastung-final-4g9ylwp3dlx/csv-mapping

The "download csv option from the CSV Mapping sometimes has a strange behavior from firefox, a new tab opens with: 
![image](https://user-images.githubusercontent.com/6167669/134888657-fe89ff6c-7925-49ff-890f-634ba68b6f73.png)

This happens on "UBD0066_Bodenbelastung_Stationen.csv " and "BD0066_Bodenbelastung_Observation.csv "
Works on "UBD0066_Bodenbelastung_Landnutzung.csv "

**Comment by l00mi** [comment]
thank you

**Comment by FabianCretton** [comment]
Today I had exactly the same problem, but I can give some more context:
- From project "UBD0104 Qualität der Badegewässer"
- I did download the 2 .csv files -> this worked fine
- Then I exported the project
- I created a new project based on that export, and I did uplad the csv files there -> this worked
- But then, on the original project, I did launch a 'transform', which failed, with errors about finding the .csv files 
https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/15623
- Then I tried to export the .csv as I did 30 minutes earlier -> same error as described in this issue

**Comment by l00mi** [comment]
I close it again for now. Please feel free to reopen if this again appears.

**Comment by FabianCretton** [comment]
Today I tried to downlaod a csv from Red Lists and got the same problem
https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!fabian-red-list-test-1-b7aqog24r6n/csv-mapping

**Comment by FabianCretton** [comment]
Michael asked me to re-import the CSV, what I did.
Then, it works again.
I will keep an eye on it, see if it happens again

**Comment by FabianCretton** [comment]
The problem is really still there, as the CSV disappeared from a new project I am working on.
The "download CSV" option opens the screen that I pasted in the first post of this issue, and the transform gives:
![image](https://user-images.githubusercontent.com/6167669/141785186-fcf11468-b5d8-4df8-b9a8-f56cbaa2200b.png)

**Comment by tpluscode** [comment]
I'm trying to make sense of what's going on here. Looking at the `UBD0066 Bodenbelastung (final)` project, @FabianCretton you have re-uploaded the missing CSVs since you'd reported this problem? Now all four files are missing from S3. I opened an issue with VSHN to see if we can get some more intel.

At any rate, I don't see why they should be gone. Cube creator only ever deletes CSVs when a source (or project) is removed or when a replacement is uploaded.

The OFPP POC basic data project may be unrelated. I can no longer access the job logs but I see that the subsequent runs succeeded...

**Comment by FabianCretton** [comment]
@tpluscode , yes, the  CSV were re-uploaded on` UBD0066 Bodenbelastung (final)`, as Véronique had to work on the project.

Please keep me informed if VSHN figures out something, and I will also report if it happens again.

**Comment by tpluscode** [comment]
Oh, sorry, I've only put 2 and 2 together today. I wrote it just above

>  Cube creator only ever deletes CSVs when [...] when a replacement is uploaded.

And that is exactly what was happening. We exported projects complete with the S3 keys of CSV sources and they were removed because the code assumed they were being replaced, as is the case typically when re-uploading.

Will be fixed with next release
