### ISSUE TITLE
It should not be possible to reactivate "transform" if a transformation is in progress. 

### ISSUE THREAD

**Issue by ortnever** [zazuko/cube-creator#887]
Sometimes the "Transform" button remains black after being activated. The user will therefore tend to reactivate it directly afterwards. At the end all transformations succeed but it takes longer. It should not be possible to reactivate "transform" if a transformation is in progress. 
![image](https://user-images.githubusercontent.com/79834090/136954888-63f28e14-8c1d-453a-933f-06b94099288d.png)

**Comment by l00mi** [comment]
Lets change the gray dot to a blinking dot to make clearer that it is running. (If possible directly remove the "green" once you click, and add the dot once the query comes back.

**Comment by l00mi** [comment]
The above is implemented and make it clear that its ongoing and takes some seconds, for the reactivate of the "transform" we put this in the backlog as it will need more decisions to take before implementing:

* Shall it be also possible to stop a pipeline? Waiting for 1h just to change a small issue would be problematic.
* Running the same pipeline multiple time will use some resources, but should work fine otherwise.

**Comment by ortnever** [comment]
I have just tested it. It's mich clearer now, with the flashing dot, that the transformation is in progress. Thanks.
The possibility to stop a pipeline could be helpful. To be discussed.
