### ISSUE TITLE
Changing the "target property" on CSV Mapping makes some value disappear in Cube Designer

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#919]
After transforming a cube, I was seeing the data in the Cube Designer.
Then I did change a property on the CSV Mapping.
I did not re-run a transform.
But on the Cube Designer, that column was then empty.
If I re-run a transform, the values appear again.
Also: if I do not re-run a transform, but change back to the former 'target property' -> the column values are back.

This seems like a bug, but also, could you explain that strong link between the CSV Mapping and a transformed cube ?
Related: we talked about the fact that we have currently no way to see that the CSV Mapping was changed after the last transform, that is correct ?
Thanks

**Comment by tpluscode** [comment]
> could you explain that strong link between the CSV Mapping and a transformed cube ?

The mappings define the shape of the cube. Specifically only the prescribed properties are loaded from observations. Thus, if you change a property, it cannot be displayed because it simply does not exist in the data. Because mapping changes do not touch the observations, when you change the property back, the data is visible again

> we talked about the fact that we have currently no way to see that the CSV Mapping was changed after the last transform, that is correct ?

With the next release we will start tracking all changes so it will be possible to provide this information. See #908. 
The initial idea was for last modification date but maybe it's more useful to know what changed since last transform as you propose.

We could update the observations on the fly but it may be wasteful to do it on every impactful change. And even more confusing if we fail to identify such changes and only handle a subset of cases.

Instead, it might be better to display a warning, even it was really general for the entire mapping screen, that something changed and it might be necessary to run trasformation

**Comment by FabianCretton** [comment]
> Instead, it might be better to display a warning, even it was really general for the entire mapping screen, that something changed and it might be necessary to run trasformation

Yes, an information that a changed has been made on CSV Mapping after the last "transform" would be helpful.

> The mappings define the shape of the cube. Specifically only the prescribed properties are loaded from observations. Thus, if you change a property, it cannot be displayed because it simply does not exist in the data. Because mapping changes do not touch the observations, when you change the property back, the data is visible again

@l00mi explaining this link between the CSV mapping and the transformed cube seems necessary in the User Guide. It is a kind-of "discovery" and surprise for me.  Maybe an explanation about the impact of changing CSV Mapping after a transform.

By the way, would it be a good/bad idea to move the "transform" button to a new tab:
1. CSV Mapping
2. Transformation
3. Cube Designer
4. Publication

Because currently the "transform" button is not inserted anywere in the steps, but I do guess that it is always the second step, no ? (and Publication has its own tab as well).

I come with those thoughts and remarks these days, as I am preparing a class that will be given about the Cube Creator on BAFU's request. I am thus having a look at the tool, given that there will be 20 people in a room, knowing nothing about RDF, and playing with the tool. Hence my more recent questions/remarks/debugging.

**Comment by l00mi** [comment]
@FabianCretton like this?
![Screenshot 2021-11-08 at 11 14 57](https://user-images.githubusercontent.com/502518/140724947-bb03a952-190d-4a98-8b9e-290b391a32c3.png)

**Comment by martinmaillard** [comment]
@l00mi Yes, exactly like your screenshot.

I personally think it's ok to have to re-run the transformation after changing the CSV mapping. It should be made clearer in the interface.

I created 2 separate issues to track the changes suggested for the UI:
- https://github.com/zazuko/cube-creator/issues/953
- https://github.com/zazuko/cube-creator/issues/954

I think we can close this one.

**Comment by l00mi** [comment]
Taking it further in the new issues. thx @martinmaillard
