### ISSUE TITLE
Special caracters in ID values allowed?

### ISSUE THREAD

**Issue by ortnever** [zazuko/cube-creator#993]
@l00mi 
When I run the "SPARQL Query" in following chart, I get an error 404 as I activate the URL of the Dimension 3  
https://int.visualize.admin.ch/en/v/-0hTlVk6_74D
It's a coincidence that I activated this link.
Maybe the reason is that I have particular caracters as values for ID? >, <

![image](https://user-images.githubusercontent.com/79834090/144053131-e7536399-ddfd-476f-9de0-eab331955f48.png)
![image](https://user-images.githubusercontent.com/79834090/144053680-b51cc5de-a7b3-4535-8525-2b04db104bad.png)

**Comment by l00mi** [comment]
That is a normal an correct behaviour to substitute "special characters" with such even more special codes for URLs. It is also called https://en.wikipedia.org/wiki/Percent-encoding.

But you have brought up a pontential problem in TRIFID (if you click on it) which seems not to properly decode this. It is in the data correct, and can be accessed through SPARQL normally. 

https://environment.ld.admin.ch/foen/ubd0037/3/beurteilung/%3EIGWLSV -> 404
https://s.zazuko.com/mmDmg -> SPARQL

I close the issue here and will investigate on the other side for trifid.

**Comment by l00mi** [comment]
@ortnever this problem was now solved in TRIFID and can be accessed by clicking on https://environment.ld.admin.ch/foen/ubd0037/3/beurteilung/%3EIGWLSV
